# Generated by Django 5.1 on 2024-09-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="contact_no",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
