# Generated by Django 5.1 on 2024-09-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hod", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffnotifications",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
