# Generated by Django 5.1 on 2024-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hod", "0003_staffleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleave",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
